#pragma once

enum CHIP_TYPE {
	CHIP_TYPE_NONE,
	CHIP_TYPE_LINE,
	CHIP_TYPE_POWERPLANT,
	CHIP_TYPE_CHARGER,
	CHIP_TYPE_FACTORY,
	CHIP_TYPE_MINER,
	CHIP_TYPE_GOLD_MINE,
	CHIP_TYPE_PIONEER,
	CHIP_TYPE_ROOT,
	CHIP_TYPE_FOREST,
	CHIP_MAX_TYPE
};